# Generated by Django 3.2.15 on 2022-08-31 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Adoption', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lost_date', models.DateField(verbose_name='Fecha de perdida')),
                ('state_found', models.BooleanField(default=False, verbose_name='Estado de encontrado')),
                ('comments', models.TextField(verbose_name='Comentario')),
                ('lost_dog', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Adoption.dog')),
            ],
        ),
    ]
