# Generated by Django 3.2.15 on 2022-10-10 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Adopciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario_adoptivo',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reunion',
            name='usuario_adoptivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adopciones.usuario_adoptivo'),
        ),
        migrations.AddField(
            model_name='esterilizacion',
            name='cam',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Adopciones.can'),
        ),
        migrations.AddField(
            model_name='can',
            name='id_raza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Adopciones.raza'),
        ),
        migrations.AddField(
            model_name='can',
            name='id_usuario_adoptivo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Adopciones.usuario_adoptivo'),
        ),
    ]
