# Generated by Django 3.2.15 on 2022-10-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adopciones', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voluntarios',
            old_name='last_name',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='voluntarios',
            old_name='authorization',
            new_name='autorizacion',
        ),
        migrations.RenameField(
            model_name='voluntarios',
            old_name='user_charge',
            new_name='cargo',
        ),
        migrations.RenameField(
            model_name='voluntarios',
            old_name='birth_date',
            new_name='fecha_nacimiento',
        ),
        migrations.RenameField(
            model_name='voluntarios',
            old_name='name',
            new_name='nombres',
        ),
        migrations.AlterField(
            model_name='voluntarios',
            name='ci',
            field=models.CharField(max_length=50, verbose_name='Carnet de identidad'),
        ),
    ]
