# Generated by Django 3.2.15 on 2022-10-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adopciones', '0003_auto_20221013_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='can',
            options={'verbose_name': 'Can', 'verbose_name_plural': 'Canes'},
        ),
        migrations.AddField(
            model_name='can',
            name='caso_independiente',
            field=models.BooleanField(default=False, verbose_name='Caso independiente'),
        ),
        migrations.AddField(
            model_name='can',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='Estado de encontrado'),
        ),
    ]
