# Generated by Django 3.2.15 on 2022-10-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adopciones', '0004_auto_20221025_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='can',
            name='nombre',
            field=models.CharField(max_length=250, unique=True, verbose_name='Nombre Can'),
        ),
    ]
