# Generated by Django 3.2.15 on 2022-10-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adopciones', '0005_alter_can_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='can',
            name='fecha_adopcion',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Fecha de adopción'),
        ),
    ]
