# Generated by Django 3.2.15 on 2022-10-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adopciones', '0006_can_fecha_adopcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='can',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado de encontrado'),
        ),
    ]
