# Generated by Django 3.2.15 on 2022-09-02 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adoption', '0002_auto_20220901_2150'),
        ('Donation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='user_sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adoption.person'),
        ),
    ]
