# Generated by Django 3.2.15 on 2022-10-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_padrino',
            field=models.BooleanField(default=False, verbose_name='Padrino'),
        ),
        migrations.AlterField(
            model_name='user',
            name='celular',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Numero telefónico'),
        ),
    ]
