# Generated by Django 3.2.15 on 2022-10-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_auto_20221013_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='celular',
            field=models.PositiveIntegerField(null=True, verbose_name='Numero telefónico'),
        ),
    ]
