# Generated by Django 3.2.15 on 2022-10-26 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registros_usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(max_length=250, verbose_name='Acción que realizo')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Detalle del movimiento')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_noticia', models.CharField(max_length=250, verbose_name='Nombre de la noticia')),
                ('imagen', models.ImageField(upload_to='Imagines_blog', verbose_name='Imagen')),
                ('comentario', models.TextField(max_length=1000, verbose_name='Comentario')),
                ('fecha', models.DateField(max_length=250, verbose_name='Fecha de publicación')),
                ('usuario_creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
