# Generated by Django 3.2.15 on 2022-09-02 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Adoption', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useradoptive',
            name='photo',
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fono', models.PositiveIntegerField(verbose_name='Numero telefónico')),
                ('photo', models.ImageField(default=None, upload_to='Usuarios', verbose_name='Foto del usuario')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='useradoptive',
            name='person_adoptive',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Adoption.person'),
        ),
    ]
